AWSTemplateFormatVersion: 2010-09-09
Description: Incident Hub Resources

Resources:
  FilesBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      BucketName: !Sub ${AWS::StackName}-files
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - HEAD
              - GET
              - PUT
              - POST
            AllowedOrigins:
              - "*"
            ExposedHeaders:
              - ETag